image: docker:git

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  DOCKER_DRIVER: overlay

services:
  - docker:dind

stages:
  - build

build_job:
  stage: build
  script:
    - apk add --update bash
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - bash generator.sh
  only:
    - master
