sudo: required

env:
  - IMAGE_NAME="identt/rancher-compose"

services:
  - docker

before_script:
  - sudo apt-get install -y git
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - bash generator.sh
